name = "finalcalc"                      # Cambia por el nombre de tu Worker
compatibility_date = "2025-06-21"
main = "index.js"                       # Archivo Worker en la raíz del proyecto

[site]
bucket = "./dist"                       # Carpeta con tus archivos estáticos (React build)
